export type Category = "Development" | "Cloud" | "AI / ML" | "Cyber Security" | "Data Science" | "Design";
export type Course = { slug: string; title: string; shortTitle: string; category: Category; summary: string; lessons: number; weeks: number; skills: string[]; tone: string; outcomes: string[]; modules: string[] };
export const categories: Category[] = ["Development", "Cloud", "AI / ML", "Cyber Security", "Data Science", "Design"];
export const courses: Course[] = [
{ slug: "full-stack-development", title: "Full-Stack Software Developer", shortTitle: "Full-Stack Development", category: "Development", summary: "Bring your ideas to life. Learn frontend, backend and everything in between.", lessons: 128, weeks: 16, skills: ["React", "Node.js", "PostgreSQL"], tone: "lime", outcomes: ["Build responsive interfaces with React and Next.js", "Design APIs and connect a relational database", "Ship a complete project for your portfolio"], modules: ["The foundations of the web", "JavaScript and TypeScript essentials", "React & Next.js fundamentals", "APIs, databases and authentication", "Your full-stack capstone project"] },
{ slug: "devops-cloud", title: "DevOps & Cloud Engineer", shortTitle: "DevOps & Cloud", category: "Cloud", summary: "Go from writing code to shipping it. Explore cloud, CI/CD and infrastructure.", lessons: 98, weeks: 12, skills: ["Docker", "Cloud", "CI/CD"], tone: "blue", outcomes: ["Understand cloud infrastructure and networking", "Containerize and deploy an application", "Build a continuous delivery pipeline"], modules: ["Linux and networking", "Cloud fundamentals", "Containers with Docker", "CI/CD pipelines", "Monitoring your application"] },
{ slug: "ai-generative-ai", title: "AI & Generative AI Engineer", shortTitle: "AI & Generative AI", category: "AI / ML", summary: "Build practical AI applications with Python, language models and real projects.", lessons: 110, weeks: 14, skills: ["Python", "LLMs", "Machine Learning"], tone: "purple", outcomes: ["Work with data and machine learning foundations", "Build an application powered by a language model", "Evaluate an AI application with useful examples"], modules: ["Python for AI", "Machine learning foundations", "Language models and prompting", "Retrieval and AI applications", "Your AI capstone project"] },
{ slug: "cyber-security", title: "Cyber Security Foundations", shortTitle: "Cyber Security", category: "Cyber Security", summary: "Understand how systems work, find weaknesses and learn to protect them.", lessons: 72, weeks: 10, skills: ["Networks", "Security", "Linux"], tone: "mint", outcomes: ["Understand common application risks", "Practice safe security analysis in a lab", "Apply secure development principles"], modules: ["Networking essentials", "Security fundamentals", "Application security", "Defensive tools", "Security lab project"] },
{ slug: "data-science", title: "Data Science & Analytics", shortTitle: "Data Science", category: "Data Science", summary: "Turn raw data into useful answers with Python, SQL and clear visualizations.", lessons: 86, weeks: 12, skills: ["Python", "SQL", "Analytics"], tone: "peach", outcomes: ["Clean and explore a dataset", "Write useful SQL queries", "Present insights in a portfolio project"], modules: ["Working with data", "Python and pandas", "SQL for analytics", "Data visualization", "Your analytics project"] },
{ slug: "ui-ux-design", title: "UI / UX & Product Design", shortTitle: "Product Design", category: "Design", summary: "Design thoughtful digital products, from your first wireframe to a polished prototype.", lessons: 64, weeks: 8, skills: ["Figma", "Research", "Prototyping"], tone: "rose", outcomes: ["Understand a user problem", "Create wireframes and interface systems", "Build and explain an interactive prototype"], modules: ["Design foundations", "Research and problem definition", "Wireframes and flows", "Interface and interaction design", "Your product case study"] },
];
export const enrollments = [{ slug: "full-stack-development", progress: 68 }, { slug: "devops-cloud", progress: 0 }, { slug: "ai-generative-ai", progress: 42 }];
export const projects = [
{ id: "task-manager", title: "Task Management App", summary: "Build a workspace where a small team can organize tasks, set priorities and track progress.", status: "In progress", skills: ["React", "Node.js", "MongoDB"], icon: "code", brief: ["Create a responsive task board with clear status columns.", "Add task creation, editing and filtering.", "Document your decisions and include setup instructions."] },
{ id: "ai-assistant", title: "AI Chat Assistant", summary: "Create a helpful assistant with a focused purpose and a clean conversational interface.", status: "Planning", skills: ["Next.js", "AI", "Python"], icon: "ai", brief: ["Choose a focused use case and explain who it helps.", "Design a clear chat interface with loading and error states.", "Document the model integration and evaluate sample conversations."] },
{ id: "portfolio", title: "Developer Portfolio", summary: "Tell the story of your work with an accessible, responsive portfolio.", status: "In progress", skills: ["HTML", "CSS", "React"], icon: "design", brief: ["Introduce yourself and your skills clearly.", "Present two projects with context, decisions and results.", "Check mobile layout and keyboard navigation."] },
];
export const tasks = [
{ id: "project", title: "Project submission", subtitle: "E-commerce website", label: "Next up", tone: "rose", kind: "project", detail: "Review your project requirements, update the README and prepare a shareable repository link." },
{ id: "live", title: "Live session", subtitle: "Node.js & Express", label: "Sample session", tone: "blue", kind: "video", detail: "This sample session covers routes, middleware and API error handling. Live session scheduling will be connected in a later phase." },
{ id: "assessment", title: "Assessment", subtitle: "JavaScript fundamentals", label: "Practice", tone: "mint", kind: "quiz", detail: "Practice arrays, objects, asynchronous code and the fundamentals of working with APIs." },
{ id: "review", title: "Code review", subtitle: "Portfolio project", label: "Upcoming", tone: "purple", kind: "code", detail: "Check your project structure, mobile layout, accessibility and README before requesting a review." },
];
export type Opportunity = { id: string; company: string; initials: string; role: string; type: "Internship" | "Job"; location: string; mode: "Remote" | "Hybrid" | "On-site"; skills: string[]; experience: string; description: string; tone: string };
export const opportunities: Opportunity[] = [
{ id: "northstar-intern", company: "Northstar Studio", initials: "N", role: "Software Developer Intern", type: "Internship", location: "Pune", mode: "Hybrid", skills: ["React", "Node.js", "MongoDB"], experience: "Students & freshers", description: "Work alongside a product team on responsive web interfaces and small API integrations. This is a sample opportunity for exploring FresherDesk.", tone: "blue" },
{ id: "orbit-frontend", company: "Orbit Labs", initials: "O", role: "Junior Frontend Developer", type: "Job", location: "Pune", mode: "On-site", skills: ["React", "TypeScript", "CSS"], experience: "0–1 years", description: "Build accessible, responsive interfaces and collaborate with designers and backend developers. This is a sample opportunity.", tone: "purple" },
{ id: "mint-ai", company: "Mint Technologies", initials: "M", role: "AI Application Intern", type: "Internship", location: "India", mode: "Remote", skills: ["Python", "AI", "APIs"], experience: "Students & freshers", description: "Prototype useful AI experiences and evaluate how they behave with real examples. This is a sample opportunity.", tone: "mint" },
{ id: "cloud-dev", company: "Cloudline", initials: "C", role: "Associate Software Engineer", type: "Job", location: "Bengaluru", mode: "Hybrid", skills: ["JavaScript", "SQL", "Git"], experience: "0–2 years", description: "Contribute to web products, learn from code reviews and build dependable software. This is a sample opportunity.", tone: "peach" },
{ id: "pixel-design", company: "Pixel & Co.", initials: "P", role: "UI / UX Design Intern", type: "Internship", location: "Pune", mode: "Remote", skills: ["Figma", "Design", "Research"], experience: "Students & freshers", description: "Explore user needs and translate ideas into thoughtful interfaces. This is a sample opportunity.", tone: "rose" },
];
export async function getCourses() { return courses; }
export async function getCourse(slug: string) { return courses.find(c => c.slug === slug); }

