"use client";
import { useSearchParams, useRouter } from "next/navigation";
import Link from "next/link";
import { Search, ArrowRight, X, SlidersHorizontal } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { CourseCard, CategoryIcon } from "./common";
import { courses, categories } from "@/lib/fresherdesk-data";
export function Catalogue() {
 const params=useSearchParams(), router=useRouter();
 const q=params.get("q")||"", requested=params.get("category")||"All";
 const category=categories.includes(requested as typeof categories[number])?requested:"All";
 const results=courses.filter(c=>(category==="All"||c.category===category)&&[c.title,c.summary,...c.skills].join(" ").toLowerCase().includes(q.toLowerCase().trim()));
 function update(key:string,value:string){const next=new URLSearchParams(params.toString());if(!value||value==="All")next.delete(key);else next.set(key,value);router.replace("/courses"+(next.size?"?"+next.toString():""),{scroll:false});}
 return <><div className="catalogue-heading"><div><span className="eyebrow">FIND YOUR NEXT CHAPTER</span><h1>Learn something.<br/><span>Build your future.</span></h1><p>Practical learning paths for wherever you want to go next.</p></div><div className="catalogue-heading-note"><span>01 — 06</span><p>Six paths.<br/>Your possibilities.</p></div></div><div className="catalogue-toolbar"><div className="search-input catalogue-search"><Search size={19}/><input value={q} onChange={e=>update("q",e.target.value)} placeholder="Search courses or skills..." aria-label="Search courses"/>{q&&<button aria-label="Clear search" onClick={()=>update("q","")}><X size={16}/></button>}</div><span className="filter-label"><SlidersHorizontal size={17}/>Find your focus</span></div><Tabs value={category} onValueChange={v=>update("category",v)} className="catalogue-tabs"><TabsList className="category-tabs">{["All",...categories].map(c=><TabsTrigger key={c} value={c}>{c}</TabsTrigger>)}</TabsList><TabsContent value={category}><div className="results-heading"><h2>{category==="All"?"Explore our courses":category}</h2><span aria-live="polite">{results.length} learning {results.length===1?"path":"paths"}</span></div>{results.length?<div className="course-grid">{results.map(c=><CourseCard key={c.slug} course={c}/>)}</div>:<div className="empty-result"><Search size={34}/><h3>No courses found</h3><p>Try another skill or explore all learning paths.</p><button className="button button-outline" onClick={()=>router.replace("/courses",{scroll:false})}>Clear filters</button></div>}</TabsContent></Tabs><div className="catalogue-help"><div><span className="eyebrow">LEARN. BUILD. KEEP GOING.</span><h2>A little progress goes a long way.</h2><p>Discover how courses, internships and real-world opportunities connect together.</p></div><Link className="button button-navy" href="/internships">Find internships<ArrowRight size={17}/></Link></div><section className="category-section"><h2>Find your area of interest</h2><div className="category-grid">{categories.map(c=><button className={"category-box"+(category===c?" selected":"")} key={c} onClick={()=>{update("category",c);window.scrollTo({top:240,behavior:"smooth"});}}><CategoryIcon category={c}/><span>{c}</span></button>)}</div></section></>;
}
