"use client";
import { useSearchParams,useRouter } from "next/navigation";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, ArrowLeft, BookOpen, Code2, ExternalLink, Check, User } from "lucide-react";
import { Tabs,TabsList,TabsTrigger,TabsContent } from "@/components/ui/tabs";
import { Input } from "@/components/ui/input";
import { courses,enrollments,projects } from "@/lib/fresherdesk-data";
import { CourseCard,CategoryIcon,CheckList,InfoDialog } from "./common";
import { ProjectCard } from "./dashboard";
import { Curriculum } from "./curriculum";
export function MyCourses(){
 const params=useSearchParams(),router=useRouter(),[filter,setFilter]=useState("all");
 const chosen=enrollments.find(e=>e.slug===params.get("course"));
 const course=chosen?courses.find(c=>c.slug===chosen.slug):null;
 const list=enrollments.filter(e=>filter==="all"||filter==="progress"&&e.progress>0&&e.progress<100||filter==="completed"&&e.progress===100);
 return <><div className="workspace-page-heading"><span className="eyebrow">YOUR LEARNING JOURNEY</span><h1>My courses</h1><p>Keep building on what you know. One lesson at a time.</p></div>{course&&chosen?<section className="dashboard-panel student-course-detail"><button className="back-link" onClick={()=>router.replace("/dashboard/courses",{scroll:false})}><ArrowLeft size={16}/>All my courses</button><div className="student-course-heading"><span className={"course-icon "+course.tone}><CategoryIcon category={course.category}/></span><div><h2>{course.title}</h2><p>{chosen.progress}% complete · Sample progress</p></div></div><p className="muted">{course.summary}</p><CheckList items={course.outcomes}/><h3>Your course outline</h3><Curriculum modules={course.modules}/><div className="learning-notice"><BookOpen size={22}/><div><b>Your learning space is taking shape.</b><p>This is a course overview preview. Lessons and progress tracking will be connected in the next stage.</p></div></div></section>:<><Tabs value={filter} onValueChange={setFilter} className="student-tabs"><TabsList className="category-tabs"><TabsTrigger value="all">All courses ({enrollments.length})</TabsTrigger><TabsTrigger value="progress">In progress</TabsTrigger><TabsTrigger value="completed">Completed</TabsTrigger></TabsList><TabsContent value={filter}>{list.length?<div className="course-grid student-course-grid">{list.map(e=><CourseCard key={e.slug} course={courses.find(c=>c.slug===e.slug)!} progress={e.progress}/>)}</div>:<div className="empty-result"><BookOpen size={32}/><h3>Your next milestone is ahead.</h3><p>No completed courses in this preview. Continue a learning path to explore its outline.</p><button className="button button-outline" onClick={()=>setFilter("all")}>View all courses</button></div>}</TabsContent></Tabs><div className="learning-notice"><BookOpen size={23}/><div><b>Ready for something new?</b><p>Explore another learning path and see where your curiosity takes you.</p></div><Link href="/courses" className="text-link">Explore courses<ArrowRight size={17}/></Link></div></>}</>;
}
export function MyProjects(){
 const params=useSearchParams(),router=useRouter(),[filter,setFilter]=useState("all"),[draft,setDraft]=useState(""),[notice,setNotice]=useState("");
 const selected=projects.find(p=>p.id===params.get("project"));
 const list=projects.filter(p=>filter==="all"||p.status===filter);
 return <><div className="workspace-page-heading"><span className="eyebrow">IDEAS INTO REALITY</span><h1>My projects</h1><p>Build something that shows what you can do.</p></div>{selected?<section className="dashboard-panel project-detail"><button className="back-link" onClick={()=>router.replace("/dashboard/projects",{scroll:false})}><ArrowLeft size={16}/>All projects</button><span className="badge mint">{selected.status}</span><h2>{selected.title}</h2><p className="muted">{selected.summary}</p><div className="skill-tags">{selected.skills.map(s=><span key={s}>{s}</span>)}</div><h3>Project brief</h3><CheckList items={selected.brief}/><form className="project-link-form" onSubmit={e=>{e.preventDefault();setNotice("Link checked. Submission will be enabled when project storage is connected.");}}><label htmlFor="project-link">Project repository or live link</label><Input id="project-link" type="url" placeholder="https://github.com/your-name/project" required value={draft} onChange={e=>{setDraft(e.target.value);setNotice("");}}/><button className="button button-navy" type="submit"><ExternalLink size={16}/>Check project link</button><p className="form-message" role="status">{notice||"You can practise adding a link here. It is not submitted or saved."}</p></form></section>:<><Tabs value={filter} onValueChange={setFilter}><TabsList className="category-tabs"><TabsTrigger value="all">All projects</TabsTrigger><TabsTrigger value="In progress">In progress</TabsTrigger><TabsTrigger value="Planning">Planning</TabsTrigger></TabsList><TabsContent value={filter}><div className="project-list">{list.map(p=><ProjectCard key={p.id} project={p}/>)}</div></TabsContent></Tabs><div className="learning-notice"><Code2 size={23}/><div><b>Small projects. Real progress.</b><p>Focus on a clear problem, build a thoughtful solution and document your decisions.</p></div></div></>}</>;
}
export function MyProfile(){
 const initial={name:"Aarav Sharma",email:"aarav@example.com",education:"B.Sc. Computer Science",location:"Pune, Maharashtra",role:"Frontend Developer",skills:"React, Next.js, JavaScript, CSS"};
 const [data,setData]=useState(initial),[notice,setNotice]=useState("");
 return <><div className="workspace-page-heading"><span className="eyebrow">YOUR STORY, YOUR WAY</span><h1>My profile</h1><p>A little about you and where you want to go.</p></div><div className="profile-layout"><aside className="dashboard-panel profile-summary"><span className="profile-large-avatar">{data.name.split(" ").filter(Boolean).slice(0,2).map(s=>s[0]).join("")||"AS"}</span><h2>{data.name||"Your name"}</h2><p>{data.role||"Your next role"}</p><span className="badge mint">Student preview</span><div className="profile-info"><User size={17}/><span>{data.location||"Your location"}</span></div><p className="preview-note">This is a sample profile. Account storage is not connected.</p></aside><section className="dashboard-panel profile-form"><h2>Personal details</h2><p className="muted">Try editing the fields to preview your profile.</p><form onSubmit={e=>{e.preventDefault();setNotice("Profile preview updated. These changes are not saved to an account.");}}><div className="form-grid">{[{key:"name",label:"Full name"},{key:"email",label:"Email address"},{key:"education",label:"Education"},{key:"location",label:"Location"},{key:"role",label:"Preferred role"},{key:"skills",label:"Skills"}].map(({key,label})=><div className="form-field" key={key}><label htmlFor={"profile-"+key}>{label}</label><Input id={"profile-"+key} type={key==="email"?"email":"text"} required value={data[key as keyof typeof data]} onChange={e=>{setData(v=>({...v,[key]:e.target.value}));setNotice("");}}/></div>)}</div><div className="form-actions"><button type="submit" className="button button-green">Preview changes<Check size={16}/></button><button type="button" className="button button-outline" onClick={()=>{setData(initial);setNotice("");}}>Reset</button></div><p className="form-message" role="status">{notice}</p></form></section></div></>;
}
